###################################################
POST http://localhost:3000/api/ingresarMovimiento
Content-Type: application/x-www-form-urlencoded

user=20180038
&password=123

fecha="2024-06-18T05:00:00.000Z
tipo_id=2
categoria_id=1
monto=100
comentario= "Gastos en comida"
usuario_id=20213134
###################################################